### PR TITLE
Build/2781: update rust-fil-proofs upstream for correct dependencies

### LINKED ISSUE #2781: [build] 0.2.2 go run ./build deps fail
**Describe the bug**
go run ./build deps fail.
report error

**To Reproduce**
cd $GOPATH/src/github.com/filecoin-project/go-filecoin
git fetch origin
git checkout $USER_DEVNET_TAG
 go run ./build deps

**Expected behavior**
go run ./build deps success

**Screenshots**
root@localhost:~/go_src/src/github.com/filecoin-project/go-filecoin# go run ./build deps
pkg-config --version
0.29.1
Installing dependencies...
go mod download
./scripts/install-rust-fil-proofs.sh
using local rust-fil-proofs
~/go_src/src/github.com/filecoin-project/go-filecoin/proofs/rust-fil-proofs ~/go_src/src/github.com/filecoin-project/go-filecoin
cargo 1.36.0-nightly (b6581d383 2019-04-16)
    Updating git repository `https://github.com/filecoin-project/bellman`
    Updating crates.io index
    Updating git repository `https://github.com/filecoin-project/pairing`
    Updating git repository `https://github.com/filecoin-project/phase2`
    Updating git repository `https://github.com/filecoin-project/sapling-crypto`
    Updating git repository `https://github.com/oconnor663/blake2s_simd`
    Updating git repository `https://github.com/tyranron/config-rs`
error: failed to load source for a dependency on `config`

Caused by:
  Unable to update https://github.com/tyranron/config-rs?branch=60-fix-defaults

Caused by:
  failed to find branch `60-fix-defaults`

Caused by:
  cannot locate local branch '60-fix-defaults'; class=Reference (4); code=NotFound (-3)
    Updating git repository `https://github.com/filecoin-project/bellman`
    Updating crates.io index
    Updating git repository `https://github.com/filecoin-project/pairing`
    Updating git repository `https://github.com/filecoin-project/phase2`

**Version information**
go version         
go version go1.12.2 linux/arm64

root@localhost:~/go_src/src/github.com/filecoin-project/go-filecoin#  rustc --version
rustc 1.34.1 (fc50f328b 2019-04-24)

cargo --version
cargo 1.34.0 (6789d8a0a 2019-04-01)

 git rev-parse HEAD
fcf56acdc98a2ea4fc4d0b62878a9302f51af869

root@localhost:~/go_src/src/github.com/filecoin-project/go-filecoin# go env 
GOARCH="arm64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="arm64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go_src"
GOPROXY=""
GORACE=""
GOROOT="/root/go"
GOTMPDIR=""
GOTOOLDIR="/root/go/pkg/tool/linux_arm64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build412356535=/tmp/go-build -gno-record-gcc-switches"

root@localhost:~/go_src/src/github.com/filecoin-project/go-filecoin# $(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version
gcc (Ubuntu/Linaro 7.4.0-1ubuntu1~18.04) 7.4.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### PR DESCRIPTION
**Pull request by imrehg**
Fixes #2781 

Upstream code has changed dependencies and previously referred branches do not exist anymore, which resulted in a build failure.

Signed-off-by: Gergely Imreh <imrehg@gmail.com>

### CODE REVIEW

**Comment by anorth** [comment]
@laser could you please shepherd this PR?

**Comment by laser** [comment]
@imrehg - Would you mind rebasing your fork branch onto the head of go-filecoin `master`? Once that build passes, I'll merge into go-filecoin.

**Comment by laser** [comment]
Tagging you also, @acruikshank, although there isn't much to review. Our PRs need 2 reviews.

**Comment by laser** [comment]
Closing in favor of #2812.

**Pull request closed without merging**
