### PR TITLE
add default for gas-price and gas-limit (#1699)

### LINKED ISSUE #1699: [bug] CLI Help when some "options" are required is self-contradicting
### Description
In several places in the CLI help, we have text that puts `--someOption` in square brackets, but such an option is required.  This is confusing, since the extended help has no indication that these things are required.  Example is the miner create help text quoted below.

If I run the miner create command as I have before (`go-filecoin miner create 10 100`), it fails, saying only that --price is required.  But both gas price and gas limit are required arguments.  In Unix help, square brackets around an argument mean it is optional, however these arguments are in square brackets in the help text.  In the "USAGE" section and the `miner --help` output, `--price` and `--limit` aren't shown at all (so the miner command help can't be used as a quick reference because it's incomplete).  In the "OPTIONS" shown below, `--price` and `--limit` also aren't marked required.

### Expected Behavior
All help text should show all required arguments. The only arguments in square brackets should be optional ones.  In the extended help (e.g. OPTIONS section), these arguments should say "required" in some way, and be the same way everywhere.

### Current Behavior
```
 $ gf miner create --help
USAGE
  go-filecoin miner create <pledge> <collateral> - Create a new file miner with <pledge> 1GB sectors and <collateral> FIL

SYNOPSIS
  go-filecoin miner create [--from=<from>] [--peerid=<peerid>] [--price=<price>] [--limit=<limit>] [--] <pledge> <collateral>

ARGUMENTS

  <pledge>     - The size of the pledge (in 1GB sectors) for the miner
  <collateral> - The amount of collateral in FIL to be sent (minimum 0.001 FIL per sector)

OPTIONS

  --from   string - Address to send from.
  --peerid string - Base58-encoded libp2p peer ID that the miner will operate.
  --price  string - Price (FIL e.g. 0.00013) to pay for each GasUnits consumed mining this message.
  --limit  uint64 - Maximum number of GasUnits this message is allowed to consume.
```

### Starting points
If there is a single default gas limit and gas price, then the default option text will need to be updated in [main.go](https://github.com/filecoin-project/go-filecoin/blob/4b6d10df1aa9ecebc6525e5a8e0d8bfbe5097660/commands/main.go#L316).

Also look in `commands/` for functions that call `parseGasOptions`:
* [message.go](https://github.com/filecoin-project/go-filecoin/blob/7cc6a6b790c3fd74e2f68c061a5e239348037b32/commands/message.go#L39)
* [miner.go](https://github.com/filecoin-project/go-filecoin/blob/4b6d10df1aa9ecebc6525e5a8e0d8bfbe5097660/commands/miner.go#L61) and other functions in this file
* [payment_channel.go](https://github.com/filecoin-project/go-filecoin/blob/4b6d10df1aa9ecebc6525e5a8e0d8bfbe5097660/commands/payment_channel.go#L68) and other functions in this file

### PR DESCRIPTION
**Pull request by deaswang**
Fixes #1699

### CODE REVIEW

**Comment by deaswang** [comment]
already rebase master. @travisperson @frrist

**Comment by deaswang** [comment]
strange, sometime pass, sometime fail at different test case here. test case should queued.

**Comment by anorth** [comment]
The values have changed since this was reviewed. Please see my comment here: https://github.com/filecoin-project/go-filecoin/pull/1896#discussion_r256598999

**Comment by travisperson** [comment]
We removed the ability for zero priced gas. (Issue https://github.com/filecoin-project/go-filecoin/issues/2523; PR https://github.com/filecoin-project/go-filecoin/pull/2605)

https://github.com/filecoin-project/go-filecoin/blob/3dbbf3a515ab9c9c48bb37da5dafc7bce77e17c0/consensus/validation.go#L67-L69

I'm not sure how these tests are passing unless the code above is dead.

**Comment by anorth** [comment]
In that case I don't think we should have a default gas price baked into the code. Until we have something more sophisticated, I think we should require users to specify a gas price, and thus a bound on their cost. cc @mishmosh for comment.

Sorry for the misdirection from #1699, @deaswang. Can we fix up the help documentation to match behaviour instead?

**Comment by deaswang** [comment]
OK. Wait for final decide. if gas price is required, it should move to Arguments. Options donot support require option.
https://godoc.org/github.com/ipfs/go-ipfs-cmdkit

**Comment by anorth** [comment]
In *that* case I think maybe we should just not fix this, and wait for #3098 and a CLI implemented on top of it to solve all our problems.

**Comment by frrist** [comment]
Sorry for the misdirection on this @deaswang, we are going to close this and reevaluate after #3098 lands.

**Pull request closed without merging**
