### PR TITLE
update go-log v0.0.2

### PR DESCRIPTION
**Pull request by frrist**
### Motivation
Update go-log to the most recent version that uses zap as a logging backend. This allows for structured logging.

### Proposed changes

Closes issue https://github.com/filecoin-project/go-filecoin/issues/2653

### CODE REVIEW

**Comment by anorth** [comment]
Could you please paste an example of what the log output now looks like? E.g. the "Track peer" message.

**Comment by frrist** [comment]
Logging output when written to console: 
```
2019-10-16T15:39:04.866-0700    INFO    chain.store     chain/store.go:138      start loading chain at tipset: { bafy2bzacectgliczuafwmqwmovck5v52qr4lwdflydtodz7ut4kfznczro6va }, height: 0
2019-10-16T15:39:04.866-0700    INFO    chain.store     chain/store.go:182      finished loading 0 tipsets from { bafy2bzacectgliczuafwmqwmovck5v52qr4lwdflydtodz7ut4kfznczro6va }
2019-10-16T15:39:05.705-0700    INFO    mining  mining/worker.go:158    Worker.Mine
2019-10-16T15:39:06.409-0700    INFO    peer-tracker    net/peer_tracker.go:81  Track peer      {"chainInfo": "{peer=QmZLh8uEHEhWM7FEu3wCZLj3JhKFpfYTadWFF1Er4o5Vsf height=0 head={ bafy2bzacectgliczuafwmqwmovck5v52qr4lwdflydtodz7ut4kfznczro6va }}", "new": true, "count": 1, "trusted": false}
2019-10-16T15:39:06.410-0700    INFO    node    node/node.go:194        initial chain sync complete! chain head height 0, tipset key { bafy2bzacectgliczuafwmqwmovck5v52qr4lwdflydtodz7ut4kfznczro6va }, blocks { bafy2bzacectgliczuafwmqwmovck5v52qr4lwdflydtodz7ut4kfznczro6va }
```

Logging output when written as JSON:
```
{"level":"info","ts":"2019-10-16T15:42:44.110-0700","logger":"autonat","caller":"go-libp2p-autonat@v0.1.0/notify.go:34","msg":"Discovered AutoNAT peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4"}
{"level":"info","ts":"2019-10-16T15:42:44.112-0700","logger":"net.graphsync_fetcher","caller":"net/graphsync_fetcher.go:181","msg":"fetching chain from height 26302, block bafy2bzaced7sjet7l7eebwsndpiabxcjvzscwthgxwy25co43vrqeff44ra4e, peer Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4, 64 levels"}
{"level":"info","ts":"2019-10-16T15:42:44.559-0700","logger":"peer-tracker","caller":"net/peer_tracker.go:81","msg":"Track peer","chainInfo":"{peer=QmZco5mhN7ihSr9MzBQtzvsEGXGtcKCbgqynB6Ve5Z6id6 height=47941 head={ bafy2bzaceb5ljo5obw72a6ydyx2bvhmmydjt5s6bdtqylmfquwhgju2rgt6ny }}","new":true,"count":2,"trusted":false}
{"level":"info","ts":"2019-10-16T15:42:44.621-0700","logger":"peer-tracker","caller":"net/peer_tracker.go:81","msg":"Track peer","chainInfo":"{peer=QmcSpQeZAqZVRYhkS2d9TzmYPAaJ3Bqz7sCuYN3815aHMM height=47941 head={ bafy2bzaceb5ljo5obw72a6ydyx2bvhmmydjt5s6bdtqylmfquwhgju2rgt6ny }}","new":true,"count":3,"trusted":false}
```

**Comment by anorth** [comment]
Ok. And I'm guessing we need to do something like add a MarshalJSON method to ChainInfo in order for it to output as structured data?

**Comment by frrist** [comment]
@anorth we don't _have_ to, lines like [this](https://github.com/filecoin-project/go-filecoin/pull/3557/files#diff-f906d24633161382dc1f3576f67252cbR81) work:
```
logPeerTracker.Infow("Track peer", "chainInfo", ci, "new", !tracking, "count", len(tracker.peers), "trusted", trusted)
```
However it would be more performant (and less verbose) to implement the `MarshalLogObject` interface on structures we intend log as it [avoids reflection](https://github.com/prashantv) (`Infow`, `Errorw`, `*w` reflect).
We can also implement `MarshalLogArray` on arrays of structures, like Blocks in TipSets.

As an aside, structures that implement the `Marshal*` interface could also work with our [Zap journal](https://github.com/filecoin-project/go-filecoin/blob/master/journal/zap.go). The drawback here is that it would tie us into a specific implementation, zap.

**Pull request merged**
