### PR TITLE
Upgrade go-fil-markets to v0.2.4

### PR DESCRIPTION
**Pull request by ingar**
### Motivation
Update the go-fil-markets interfaces to match v0.2.4.

### Proposed changes
Update go-fil-markets, storage market Client and Provider node interface.

Closes https://github.com/filecoin-project/go-fil-markets/issues/238

### CODE REVIEW

**Comment by hannahhoward** [comment]
@anorth just a heads up that this is an initial but not sufficient PR to prove deals are working in GFC.

**Comment by hannahhoward** [comment]
more are coming

**Comment by laser** [comment]
Note: This PR will eliminate lotus from the go-filecoin dependency graph, which is a good thing IMHO.

**Comment by anorth** [comment]
😱 😭

**Pull request merged**
