### PR TITLE
add default values for gas stuff

### PR DESCRIPTION
**Pull request by whyrusleeping**
This makes it much nicer to use filecoin.

### CODE REVIEW

**Comment by phritz** [comment]
@mishmosh can you expand on what you think needs to change re cli and wiki?

**Comment by mishmosh** [comment]
If we move forward with this PR here are the docs that need updating:
- wiki mining tutorial, explicit gas values can be deleted from the example
- wiki commands page, gas values can be in brackets to show they're optional
- CLI helptext for this command, gas values should be in brackets to show they are optional

**Comment by laser** [comment]
@acruikshank @anorth - Is this PR dead? If not: What needs to happen to move it forward?

**Comment by anorth** [comment]
It could move forward if someone commits to addressing the comments and updating documentation after landing it. Alternatively, I don't think it's high priority, so could be abandoned in favour of another go later.

Future client libraries will probably automate some of this with chain-inspection based estimates of the gas market price.

**Comment by frrist** [comment]
Closing as this is now being addressed via https://github.com/filecoin-project/go-filecoin/pull/3118

**Pull request closed without merging**
