### PR TITLE
heartbeat conn failure is warning

### PR DESCRIPTION
**Pull request by frrist**

### CODE REVIEW

**Comment by anorth** [comment]
The current behaviour is intentional. See https://github.com/filecoin-project/go-filecoin/issues/1906 and https://github.com/filecoin-project/go-filecoin/pull/2023

**Comment by gmasgras** [comment]
We have 3 devnets running and only one (usernet) connects to the heartbeat service that feeds the dashboard at `stats.kittyhawk.wtf`. 
This results in the other 2 devnets spamming with non-actionable alerts every 10min.
Can we introduce an ENV that turns this into a warning when specified ?

**Comment by anorth** [comment]
It sounds to me like we need a more general solution to ignoring, or at least siloing, warnings/errors from networks that aren't the devnet.

If the nightly net doesn't connect to `stats`, then it should probably be configured to *not connect*, and hence not fail, rather than downgrade this message.

**Comment by frrist** [comment]
@gmasgras is there a way to avoid passing the environment variable `FIL_HEARTBEAT_ALERTS`  to the test and nightly devnets?

**Comment by gmasgras** [comment]
> @gmasgras is there a way to avoid passing the environment variable `FIL_HEARTBEAT_ALERTS` to the test and nightly devnets?

I think we still want to pass that in, as we would stop getting alerts about nodes that are out of consensus or no blocks mined for $interval.

**Comment by frrist** [comment]
After some discussion with @gmasgras we will close this in favor of a different approach

**Pull request closed without merging**
