### PR TITLE
 Fix golangci-lint warnings 

### PR DESCRIPTION
**Pull request by magik6k**
Required for https://github.com/filecoin-project/go-filecoin/issues/2207.

There seem to be some issues with daemon tests, but I'm not sure what causes that (also, circle seems dead - https://status.circleci.com/)

### CODE REVIEW

**Comment by Stebalien** [comment]
The errors look like real issues:

```
--- FAIL: TestUpdateMessagePool (0.07s)
    --- PASS: TestUpdateMessagePool/Replace_head (0.00s)
    message_pool_test.go:201: 
        	Error Trace:	message_pool_test.go:201
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_head_with_self (0.00s)
    message_pool_test.go:227: 
        	Error Trace:	message_pool_test.go:227
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_head_with_a_long_chain (0.00s)
    message_pool_test.go:251: 
        	Error Trace:	message_pool_test.go:251
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_head_with_multi-block_tipset_chains (0.01s)
    message_pool_test.go:271: 
        	Error Trace:	message_pool_test.go:271
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_internal_node_(second_one) (0.00s)
    message_pool_test.go:300: 
        	Error Trace:	message_pool_test.go:300
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_internal_node_(second_one)_with_a_long_chain (0.00s)
    message_pool_test.go:327: 
        	Error Trace:	message_pool_test.go:327
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_internal_node_with_multi-block_tipset_chains (0.00s)
    message_pool_test.go:353: 
        	Error Trace:	message_pool_test.go:353
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Replace_with_same_messages_in_different_block_structure (0.01s)
    message_pool_test.go:374: 
        	Error Trace:	message_pool_test.go:374
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Truncate_to_internal_node (0.00s)
    message_pool_test.go:394: 
        	Error Trace:	message_pool_test.go:394
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Extend_head (0.00s)
    message_pool_test.go:418: 
        	Error Trace:	message_pool_test.go:418
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Extend_head_with_a_longer_chain_and_more_messages (0.00s)
    message_pool_test.go:444: 
        	Error Trace:	message_pool_test.go:444
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:444: 
        	Error Trace:	message_pool_test.go:444
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:444: 
        	Error Trace:	message_pool_test.go:444
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:444: 
        	Error Trace:	message_pool_test.go:444
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:444: 
        	Error Trace:	message_pool_test.go:444
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    --- PASS: TestUpdateMessagePool/Times_out_old_messages (0.01s)
    message_pool_test.go:499: 
        	Error Trace:	message_pool_test.go:499
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:499: 
        	Error Trace:	message_pool_test.go:499
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:499: 
        	Error Trace:	message_pool_test.go:499
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:499: 
        	Error Trace:	message_pool_test.go:499
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
    message_pool_test.go:499: 
        	Error Trace:	message_pool_test.go:499
        	Error:      	Received unexpected error:
        	            	empty tipset calling unallowed method
        	            	github.com/filecoin-project/go-filecoin/types.init
        	            		/go/src/github.com/filecoin-project/go-filecoin/types/tipset.go:20
        	            	github.com/filecoin-project/go-filecoin/chain.init
        	            		<autogenerated>:1
        	            	github.com/filecoin-project/go-filecoin/core.init
        	            		<autogenerated>:1
        	            	main.init
        	            		<autogenerated>:1
        	            	runtime.main
        	            		/usr/local/go/src/runtime/proc.go:189
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1333
        	Test:       	TestUpdateMessagePool
```

**Comment by Stebalien** [comment]
Fix in #2305.

**Comment by anorth** [comment]
Thanks! @frrist could you please shepherd this PR (review it when ready, add maintainer review, then land it)?

**Comment by Stebalien** [comment]
(rebased)

**Comment by magik6k** [comment]
(rebased again)

**Comment by frrist** [comment]
(rebased again again)

**Pull request merged**
