### PR TITLE
Fix broken references to old sector store type.

### PR DESCRIPTION
**Pull request by anorth**
Broken in 79bba96d9426a1b2ebba62fc12a5dd76c63f1c93

### CODE REVIEW

**Comment by RobQuistNL** [comment]
On master;
```
Building go-filecoin...
git log -n 1 --format=%H
go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=1a2212e17d757d793ac6f3ae2c4d80272b680657 -v -o go-filecoin .
Building gengen utils...
go build -o ./gengen/gengen ./gengen
Building faucet...
go build -o ./tools/faucet/faucet ./tools/faucet/
Building genesis file server...
go build -o ./tools/genesis-file-server/genesis-file-server ./tools/genesis-file-server/
Generating genesis...
./gengen/gengen --keypath fixtures --out-car fixtures/genesis.car --out-json fixtures/gen.json --config ./fixtures/setup.json
```
(still works somehow)

On this branch:
```
go run ./build buildBuilding go-filecoin...
git log -n 1 --format=%H
go build -ldflags -X github.com/filecoin-project/go-filecoin/flags.Commit=a1331ee6f9a25aacc1b5a2c0b9f6600188103d9b -v -o go-filecoin .
github.com/filecoin-project/go-filecoin/proofs
github.com/filecoin-project/go-filecoin/proofs/sectorbuilder
github.com/filecoin-project/go-filecoin/types
github.com/filecoin-project/go-filecoin/abi
github.com/filecoin-project/go-filecoin/actor/builtin/miner
github.com/filecoin-project/go-filecoin/protocol/retrieval
github.com/filecoin-project/go-filecoin/actor/builtin/storagemarket
github.com/filecoin-project/go-filecoin/actor/builtin
github.com/filecoin-project/go-filecoin/consensus
github.com/filecoin-project/go-filecoin/gengen/util
github.com/filecoin-project/go-filecoin/mining
github.com/filecoin-project/go-filecoin/chain
github.com/filecoin-project/go-filecoin/core
github.com/filecoin-project/go-filecoin/testhelpers
github.com/filecoin-project/go-filecoin/plumbing/msg
github.com/filecoin-project/go-filecoin/porcelain
github.com/filecoin-project/go-filecoin/protocol/storage
github.com/filecoin-project/go-filecoin/node
github.com/filecoin-project/go-filecoin/commands
Building gengen utils...
go build -o ./gengen/gengen ./gengen
Building faucet...
go build -o ./tools/faucet/faucet ./tools/faucet/
Building genesis file server...
go build -o ./tools/genesis-file-server/genesis-file-server ./tools/genesis-file-server/
Generating genesis...
./gengen/gengen --keypath fixtures --out-car fixtures/genesis.car --out-json fixtures/gen.json --config ./fixtures/setup.json
```

LGTM :+1:

**Comment by laser** [comment]
## Postmortem

### How did this failure manifest?

The last commit on the branch `feat/2530-rename-to-proofs-mode` passed the CI build:

https://circleci.com/workflow-run/696b2546-4519-4e80-a497-f9efbb7d952d

Then, when the PR was squash-merged into `master` as commit `79bba9`, the build `master` build broke.

### Why did this happen?

The branch had not been rebased on to `master` before squash-merging. The last commit from `master` in the `feat/2530-rename-to-proofs-mode` branch was `e3f7439e`. Commit `1a2212e1` made it into `master` before the branch was merged, and that commit was incompatible with `79bba9`.

### Reproducing the failure

This failure can be reproduced by checking out the branch `feat/2530-rename-to-proofs-mode` and then cherry-picking commit `1a2212e1`. Then, run `deps` followed by `best`.

### Recommendations

If we, as a team, want to reduce the chances of this happening in the future to ~0%, we need to re-enable the GitHub branch-must-be-up-to-date-before-merging feature.

**Comment by anorth** [comment]
Thank you @laser. I personally am willing to accept occasional breakages if it reduces friction merging PRs, but we will enable the "up to date" branch check and see how we like it.

**Comment by laser** [comment]
Sounds good, @anorth. Thanks for taking the time to chat about it in-person.

**Pull request merged**
