### PR TITLE
Rename --price to --gas-price and --limit to --gas-limit

### LINKED ISSUE #1889: rename --price and --limit to be --gas-price and --gas-limit
- wiki should be updated as well
- check w/gmasgras about devnet startup scripts if they need to change
- check w/travisperson about fast whether/how it needs to change

### PR DESCRIPTION
**Pull request by mslipper**
Closes #1889.

- [x] Check with @gmasgras about the devnet scripts
- [x] Check with @travisperson about fast

### CODE REVIEW

**Comment by travisperson** [comment]
Ah cool! Depending on when this lands updating fast should be simple. Currently you can ignore any updates that might be required for FAST.

**Comment by anorth** [comment]
@travisperson could you please shepherd this PR?

**Comment by phritz** [comment]
please dont forget the update-the-wiki part of the acceptance criteria

**Comment by travisperson** [comment]
@anorth 

> @travisperson could you please shepherd this PR?

What does this mean?

**Comment by anorth** [comment]
@travisperson I mean be the committer who will land these changes once review is complete. People outside the committer group can't merge.

https://github.com/filecoin-project/go-filecoin/blob/master/CONTRIBUTING.md#pull-requests-and-reviews

**Comment by mslipper** [comment]
I'll fix conflicts + the build.

**Comment by mslipper** [comment]
Boom, ready to merge.

**Comment by mslipper** [comment]
@gmasgras will update `go-filecoin-infra` to reflect the new CLI args.

**Comment by gmasgras** [comment]
> @gmasgras will update `go-filecoin-infra` to reflect the new CLI args.

https://github.com/filecoin-project/go-filecoin-infra/pull/185

**Pull request merged**
