### PR TITLE
update libp2p to 6.0.33

### PR DESCRIPTION
**Pull request by ZenGround0**

### CODE REVIEW

**Comment by ZenGround0** [comment]
@acruikshank lots of tests failing.  Looks like a mix of refmt and libp2p mock failures.

**Comment by travisperson** [comment]
There is an issue with an incorrect version of `go-libp2p-peer` reference in FAST still (I assume zen forgot to add these files because he was running into other issues), such that it didn't get picked up when you updated things.

```diff
diff --git a/tools/fast/actions_swarm.go b/tools/fast/actions_swarm.go
index 7e2fbec4..8d84ce12 100644
--- a/tools/fast/actions_swarm.go
+++ b/tools/fast/actions_swarm.go
@@ -5,7 +5,7 @@ import (
 	"io"
 
 	"gx/ipfs/QmNTCey11oxhb1AxDnQBRHtdhap6Ctud872NjAYPYYXPuc/go-multiaddr"
-	"gx/ipfs/QmcqU6QUDSXprb1518vYDGczrTJTyGwLG9eUa5iNX4xUtS/go-libp2p-peer"
+	"gx/ipfs/QmPJxxDsX2UbchSHobbYuvz7qnyJTFKvaKMzE2rZWJ4x5B/go-libp2p-peer"
 
 	"github.com/filecoin-project/go-filecoin/api"
 )
diff --git a/tools/fast/process_action_options.go b/tools/fast/process_action_options.go
index d469059f..f21e44fb 100644
--- a/tools/fast/process_action_options.go
+++ b/tools/fast/process_action_options.go
@@ -4,7 +4,7 @@ import (
 	"fmt"
 	"math/big"
 
-	"gx/ipfs/QmcqU6QUDSXprb1518vYDGczrTJTyGwLG9eUa5iNX4xUtS/go-libp2p-peer"
+	"gx/ipfs/QmPJxxDsX2UbchSHobbYuvz7qnyJTFKvaKMzE2rZWJ4x5B/go-libp2p-peer"
 
 	"github.com/filecoin-project/go-filecoin/address"
 )
```

After fixing that, I'm now seeing the mock missing implementations of our libp2p host.

https://github.com/filecoin-project/go-filecoin/blob/7a875edf5eb423bf8011a0437f26ceac5f1511be/node/libp2p.go#L64-L66

We use a `noopLibP2PHost{}` when we run a node in offline mode.

https://github.com/filecoin-project/go-filecoin/blob/1842397d06c4734779120cec01eaf542ed18e91d/api/impl/dag_test.go#L31-L36

```
panic: implement me [recovered]
	panic: implement me

goroutine 1074 [running]:
testing.tRunner.func1(0xc000101100)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:792 +0x387
panic(0x1142920, 0x14b9630)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/runtime/panic.go:513 +0x1b9
github.com/filecoin-project/go-filecoin/node.noopLibP2PHost.ConnManager(0xc01bcfba70, 0x0)
	/home/travis/src/github.com/filecoin-project/go-filecoin/node/libp2p.go:65 +0x39
gx/ipfs/QmebEmt23jQxrwnqBkFL4qbpE8EnnQunpv5U32LS5ESus1/go-libp2p/p2p/host/routed.(*RoutedHost).ConnManager(0xc01bcd1800, 0xc01be35900, 0x4a2d48)
	/home/travis/src/gx/ipfs/QmebEmt23jQxrwnqBkFL4qbpE8EnnQunpv5U32LS5ESus1/go-libp2p/p2p/host/routed/routed.go:184 +0x33
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/network.(*impl).ConnectionManager(0xc01bd02ac0, 0xc01bcfba70, 0xc01be35938)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/network/ipfs_impl.go:208 +0x33
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap.New.func4(0x14c8bc0, 0xc01bd03000, 0x1, 0xc01bd03000, 0xc01bcfba70)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/bitswap.go:112 +0x3c
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/sessionmanager.(*SessionManager).NewSession(0xc01bc8a840, 0x14c8bc0, 0xc01bd02fc0, 0x10, 0xc01bcfba60)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/sessionmanager/sessionmanager.go:71 +0xba
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap.(*Bitswap).GetBlocks(0xc01077e000, 0x14c8bc0, 0xc01bd02fc0, 0xc01bcfba60, 0x1, 0x1, 0x114d080, 0xc01bd02f01, 0xc01bcfba60)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/bitswap.go:240 +0x4a
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap.(*Bitswap).GetBlocks-fm(0x14c8bc0, 0xc01bd02fc0, 0xc01bcfba60, 0x1, 0x1, 0xc000030370, 0x5, 0x12bd745)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/bitswap.go:217 +0x5c
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/getter.SyncGetBlock(0x14c8bc0, 0xc01bd02f40, 0xc01bd09980, 0x26, 0xc01be35c08, 0x0, 0x0, 0x0, 0x0)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/getter/getter.go:39 +0x113
gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap.(*Bitswap).GetBlock(0xc01077e000, 0x14c8bc0, 0xc01bd02f40, 0xc01bd09980, 0x26, 0x14bebc0, 0xc00007b380, 0x12cab59, 0x1b)
	/home/travis/src/gx/ipfs/Qmf9HEDC317JbdByx7jUzDzcG8HtfEPYDaf8QRmovweuLT/go-bitswap/bitswap.go:217 +0x7b
gx/ipfs/QmZuPasxd7fSgtzRzCL7Z8J8QwDJML2fgBUExRbQCqb4BT/go-blockservice.getBlock(0x14c8bc0, 0xc01bd02f40, 0xc01bd09980, 0x26, 0x14cd1c0, 0xc01bcd17c0, 0xc01be35d48, 0x1, 0xc01bcfba10, 0xc01be35d58, ...)
	/home/travis/src/gx/ipfs/QmZuPasxd7fSgtzRzCL7Z8J8QwDJML2fgBUExRbQCqb4BT/go-blockservice/blockservice.go:230 +0x2f5
gx/ipfs/QmZuPasxd7fSgtzRzCL7Z8J8QwDJML2fgBUExRbQCqb4BT/go-blockservice.(*blockService).GetBlock(0xc010794780, 0x14c8bc0, 0xc01bd02f40, 0xc01bd09980, 0x26, 0x11b8640, 0x1234600, 0x14c2ac0, 0xc19ca2)
	/home/travis/src/gx/ipfs/QmZuPasxd7fSgtzRzCL7Z8J8QwDJML2fgBUExRbQCqb4BT/go-blockservice/blockservice.go:206 +0x16b
gx/ipfs/QmQvMsV5aPyd7eMd3U1hvAUhZEupG3rXbVZn7ppU5RE6bt/go-merkledag.(*dagService).Get(0xc01bcfba00, 0x14c8bc0, 0xc01bd02f40, 0xc01bd09980, 0x26, 0x0, 0x0, 0x0, 0x0)
	/home/travis/src/gx/ipfs/QmQvMsV5aPyd7eMd3U1hvAUhZEupG3rXbVZn7ppU5RE6bt/go-merkledag/merkledag.go:71 +0xf6
github.com/filecoin-project/go-filecoin/api/impl.(*nodeDag).Get(0xc01bc50180, 0x14c8c40, 0xc01be0a000, 0xc01bc97dc0, 0x34, 0xc01bde8020, 0x58e180, 0xc01b4d1901, 0xc016151940)
	/home/travis/src/github.com/filecoin-project/go-filecoin/api/impl/dag.go:34 +0x1f4
github.com/filecoin-project/go-filecoin/api/impl.TestDagGet.func2(0xc000101100)
	/home/travis/src/github.com/filecoin-project/go-filecoin/api/impl/dag_test.go:41 +0x19a
testing.tRunner(0xc000101100, 0x1418388)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:878 +0x353
FAIL	github.com/filecoin-project/go-filecoin/api/impl	2.784s
```

This appears to be from a change in `go-bitswap` where we are no longer passing the network in, but just the connection manager, hence the additional of the call to `ConnManager`. To around around this quick, I just returned `nil` (probably can find something better).

https://github.com/ipfs/go-bitswap/pull/60/files#diff-0e99f1e85b5e90e54545f9cf6d323debR115

Last thing I think we are running into is the refmt thing zen mentioned, we are registering this though.

https://github.com/filecoin-project/go-filecoin/blob/update/go-libp2p/actor/builtin/miner/miner.go#L25

```
=== RUN   TestMinerGetAsk
--- FAIL: TestMinerGetAsk (0.00s)
panic: missing an atlas entry describing how to marshal type miner.Ask (and auto-atlasing for structs is not enabled) [recovered]
	panic: missing an atlas entry describing how to marshal type miner.Ask (and auto-atlasing for structs is not enabled)

goroutine 11 [running]:
testing.tRunner.func1(0xc0003f6600)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:792 +0x387
panic(0xe8e020, 0xc0004a6b40)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/runtime/panic.go:513 +0x1b9
github.com/filecoin-project/go-filecoin/porcelain.(*minerGetAskPlumbing).MessageQuery(0x16ef458, 0x10f3b80, 0xc0000240d0, 0x0, 0x0, 0x0, 0xc012f6ce0566d0c0, 0x6c055d4c36c617e2, 0xc0e3340648, 0xf3abca, ...)
	/home/travis/src/github.com/filecoin-project/go-filecoin/porcelain/miner_test.go:397 +0x190
github.com/filecoin-project/go-filecoin/porcelain.MinerGetAsk(0x10f3b80, 0xc0000240d0, 0x10ee4c0, 0x16ef458, 0xf6ce0566d0c00000, 0x5d4c36c617e2c012, 0xe33406486c05, 0x4, 0xf, 0x15585c9, ...)
	/home/travis/src/github.com/filecoin-project/go-filecoin/porcelain/miner.go:224 +0x117
github.com/filecoin-project/go-filecoin/porcelain.TestMinerGetAsk(0xc0003f6600)
	/home/travis/src/github.com/filecoin-project/go-filecoin/porcelain/miner_test.go:406 +0xeb
testing.tRunner(0xc0003f6600, 0x1082558)
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/home/travis/.asdf/installs/golang/1.11.2/go/src/testing/testing.go:878 +0x353
exit status 2
FAIL	github.com/filecoin-project/go-filecoin/porcelain	0.040s
```

**Comment by whyrusleeping** [comment]
mmm, i didnt see this, but I went ahead and updated every single dependency (including go-libp2p) here: https://github.com/filecoin-project/go-filecoin/pull/2036

**Comment by mishmosh** [comment]
That was a premature close. To complete, verify that this works in devnet (maybe already in separate issue).

**Comment by ZenGround0** [comment]
Yup @whyrusleeping closed down #1829 with #2036

**Pull request closed without merging**
