### PR TITLE
Fix go-filecoin on go 1.12.1

### LINKED ISSUE #2167: Filecoin doesn't work with go 1.12
### Description

When using go version 1.12, filecoin experiences some problems:
1. The BLS signature code will not compile. The compiler returns these errors:
```
# github.com/filecoin-project/go-filecoin/bls-signatures [github.com/filecoin-project/go-filecoin/bls-signatures.test]
bls-signatures/bls.go:26:130: cannot use _cgo1 (type int) as type _Ctype_int in argument to _Cfunc_GoBytes
bls-signatures/bls.go:87:139: cannot use _cgo1 (type int) as type _Ctype_int in argument to _Cfunc_GoBytes
bls-signatures/bls.go:101:143: cannot use _cgo1 (type int) as type _Ctype_int in argument to _Cfunc_GoBytes
bls-signatures/bls.go:125:139: cannot use _cgo1 (type int) as type _Ctype_int in argument to _Cfunc_GoBytes
bls-signatures/bls.go:144:140: cannot use _cgo1 (type int) as type _Ctype_int in argument to _Cfunc_GoBytes
```
2. The test suite will not successfully run. Initialization of the filecoin repo produces the following error output:
```
=== RUN   TestWalletExportImportRoundTrip
--- FAIL: TestWalletExportImportRoundTrip (0.91s)
    address_daemon_test.go:126: run: go-filecoin init [--repodir=/var/folders/4n/c7j1brs57pl3g71lyqjnp3c40000gn/T/go-fil-test042674585 --genesisfile=/Users/ryankowalick/Projects/go/src/github.com/filecoin-project/go-filecoin/fixtures/genesis.car]
    commands.go:815: () run: "init --repodir=/var/folders/4n/c7j1brs57pl3g71lyqjnp3c40000gn/T/go-fil-test042674585 --genesisfile=/Users/ryankowalick/Projects/go/src/github.com/filecoin-project/go-filecoin/fixtures/genesis.car"
    address_daemon_test.go:126: initializing filecoin node at /var/folders/4n/c7j1brs57pl3g71lyqjnp3c40000gn/T/go-fil-test042674585
        badger 2019/03/05 10:33:52 INFO: All 0 tables opened in 0s
        badger 2019/03/05 10:33:52 INFO: All 0 tables opened in 0s
        badger 2019/03/05 10:33:52 INFO: All 0 tables opened in 0s
        badger 2019/03/05 10:33:52 INFO: All 0 tables opened in 0s
        badger 2019/03/05 10:33:53 INFO: Storing value log head: {Fid:0 Len:43 Offset:3830}
        badger 2019/03/05 10:33:53 INFO: Force compaction on level 0 done
        badger 2019/03/05 10:33:53 INFO: Storing value log head: {Fid:0 Len:42 Offset:134}
        badger 2019/03/05 10:33:53 INFO: Force compaction on level 0 done
        badger 2019/03/05 10:33:53 INFO: Storing value log head: {Fid:0 Len:42 Offset:803}
        badger 2019/03/05 10:33:53 INFO: Force compaction on level 0 done
        badger 2019/03/05 10:33:53 WARNING: While forcing compaction on level 0: Unable to fill tables
        Error: sync /dev/stderr: bad file descriptor
        
    address_daemon_test.go:126: exit status 1
```

### Acceptance criteria

go-filecoin compiles and tests pass when using go 1.12

### Risks + pitfalls

Unknown

### Protocol Changes

None

### Where to begin

BLS signature code compilation and looking into how badgerds logging works.

### PR DESCRIPTION
**Pull request by Stebalien**
fixes #2167

### CODE REVIEW

**Comment by anorth** [comment]
Awesome, thank you @Stebalien 

@rkowalick could you please shepherd this PR (review, add maintainer, and then land it)?

**Comment by rkowalick** [comment]
@Stebalien Is the newer version of go-ipfs-cmds compatible with go 1.11?

If it is, I don't think we should prevent the use of 1.11.

If it isn't, this PR is gtg after resolving the (hopefully trivial) conflict.

**Comment by Stebalien** [comment]
> Is the newer version of go-ipfs-cmds and our move to go modules compatible with go 1.11?

It is. I can make the version selection more flexible (we need to skip 1.12).

However, to 1.12(.1) fixes some parallel builds issues with go modules (https://golang.org/doc/go1.12#modules) so we'll probably want to bump the minimum version for that anyways.

**Comment by rkowalick** [comment]
I'm fine with either requiring 1.12.1 now or later. We're going to have to upgrade sooner or later.

**Pull request merged**
